audit_header: false
title: New Hampshire Real Estate Video Blog with Corina Cisneros
description: Our mission at Cisneros Realty Group, Llc. is to be your best resource for New Hampshire real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Cisneros Realty Group, Llc., your professional New Hampshire Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Corina Cisneros
  title:
  license_number:
  about_markdown: |
    More than an agent, I am an advocate for the interests of my clients, and my clients always come first! I am highly responsive to my client’s needs. I return phone calls, I do what I say I'm going to do and I fiercely protect my client's interests. I formed Cisneros Realty Group to increase our level of customer service even higher and expand our regional service coverage as the best Real Estate team to help you sell or buy your next home in the New Hampshire. I’ve been in love with New Hampshire since I was in middle school and learned to ski at Cannon Mountain in Franconia over 40 years ago. In 2013 I bought a second home on the shores of Lake Winnisquam and a boat, and it wasn't long before the Lakes Region finally seduced me to stay permanently. I am and avid boater and downhill skier. I find great enjoyment in riding my road bicycle. I love my 3 dogs and my a cat. I am a fanatic of Apple products, love technology and film. I have been a private pilot since 1988 and when I fly I experience peace and freedom – in good weather only of course!
  brand: Cisneros Realty Group, Llc.
  brokerage: eXp Realty
  market: New Hampshire
  address: 6 Loudon Rd. Suite 504, Concord, NH 03301
  phone: 603-273-6160
  phone_type:
  phone2:
  phone2_type:
  email: Corina@CisnerosRealtyGroup.com
  url: http://NHLakesHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.nhlakeshomes.com/homevalue/default
  second_CTA_text: Home Search
  second_CTA_URL: https://www.nhlakeshomes.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your New Hampshire Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.nhlakeshomes.com/homevalue/default

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a New Hampshire Home?"
    CTA_text2: "Search the entire MLS for your New Hampshire home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.nhlakeshomes.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'New Hampshire Real Estate Podcast with Corina Cisneros'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the New Hampshire Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Cisneros Realty Group, Llc. - your professional New Hampshire Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in New Hampshire, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Corina Cisneros'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: New Hampshire Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#ba2131'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#ba2131'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
